export { default as Anime } from './Anime';
export { default as Collections } from './Collections';
export { default as Home } from './Home';
export { default as News } from './News';
export { default as Terms } from './Terms';
export { default as Header } from './Header';
export { default as Footer } from './Footer';
export { default as Watch } from './Watch';
export { default as Main } from './Main';
